version: '3.4'

services:
    backend:
        image: react-weatherapp-backend:latest
        container_name: backend
        build:
            dockerfile: Dockerfile
            context: ./backend
            args:
                API_KEY: ${API_KEY}
        ports:
            - "9000:9000"
        volumes:
            - ./backend/src:/usr/src/app/src

    frontend:
        image: react-weatherapp:latest
        container_name: frontend
        build:
            args:
                REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/usr/src/app/src
        depends_on:
            - backend

    nginx:
        depends_on:
          - backend
          - frontend
        restart: always
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        build:
          dockerfile: Dockerfile
          context: ./nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx:/etc/nginx/conf.d
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot

    certbot:
        image: certbot/certbot
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
